// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smanfadttvujydquohcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtYW5mYWR0dHZ1anlkcXVvaGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDQxMjQsImV4cCI6MjA2MDA4MDEyNH0.MAo8VwFuU9Tdp0wFCzdPsK93j_FEi53xIqwWl659poc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);